apiVersion: v2
name: vector-standard
description: Umbrella Helm chart for Vector Standard services (API and Synchronizer)
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
