environment: &environment np

global:
  tracing: {}
  metrics: {}
  mclabels:
    environment: "development"

mclabels: &mclabels
  owner: vector
  partOf: vector-standard
  component: backend
  logScraping: true
  prometheus:
    enabled: true
    port: 8080
    path: /metrics

cloudProvider:
  flavor: &cloudProviderFlavor openshift
  dockerRegistryUrl: &dockerRegistryUrl ''
  imagePullSecretName: &pullSecret ''

dbConfig: &dbConfig
  host: host
  port: 5432
  username: postgres
  password: postgres
  database: postgres
  schema: public
  type: postgres
  sslAuth:
    enabled: false
    secretName: secret-name
    cert: ''
    key: ''
    root: ''

api:
  enabled: true
  replicaCount: 1
  revisionHistoryLimit: 5
  environment: *environment
  initialDelaySeconds: 60

  cloudProvider:
    flavor: *cloudProviderFlavor
    dockerRegistryUrl: *dockerRegistryUrl
    imagePullSecretName: *pullSecret

  image:
    repository: standard-api
    pullPolicy: Always
    tag: "v1.1.0"

  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  livenessProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    path: /liveness

  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    path: /liveness

  caSecretName: ''
  caPath: '/usr/local/share/ca-certificates'
  caKey: 'ca.crt'

  env:
    port: 80
    targetPort: 8080
    protocol: TCP
    logLevel: info
    logPrettyPrintEnabled: false
    responseCompressionEnabled: true
    requestPayloadLimit: 1mb
    tracing:
      enabled: false
      url: http://localhost:4318/v1/traces
      ratio: 1
    metrics:
      enabled: false
      url: http://localhost:55681/v1/metrics
  db: *dbConfig

  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  route:
    enabled: true
    host: ""
    path: /
    timeout:
      enabled: true # defaults to 30s by openshift
      duration: 900s # supported units (us, ms, s, m, h, d)
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

  mclabels: *mclabels

synchronizer:
  enabled: true
  replicaCount: 1
  revisionHistoryLimit: 5
  resetOnConfigChange: false

  nameOverride: ""
  fullnameOverride: ""

  ca:
    caSecretName: ''
    caPath: '/usr/local/share/destination/ca-certificates'
    caKey: 'ca.crt'

  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  livenessProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    path: /liveness

  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    path: /liveness

  cloudProvider:
    flavor: *cloudProviderFlavor
    dockerRegistryUrl: *dockerRegistryUrl
    imagePullSecretName: *pullSecret

  image:
    repository: standard-synchronizer
    pullPolicy: Always
    tag: "v1.2.0"

  layers:
  - layerName: buildings_polygon
    enums: [ code, attribute ]

  aliases:
    "*":
      num_floors: "number_of_floors"

  typeMap:
    enabled: false
    data:
      types: {}
      geometrySubTypes: {}

  env:
    port: 80
    targetPort: 8080
    protocol: TCP
    logLevel: info
    logPrettyPrintEnabled: false
    tracing:
      enabled: false
      url: http://localhost:4318/v1/traces
      ratio: 1
    metrics:
      enabled: false
      url: http://localhost:55681/v1/metrics
    schedule: '*/1 * * * *'
    indexNameFormat: '{layerName}_{column}_idx'
    layersFile: /usr/src/app/packages/synchronizer/dist/config/layers/layers.json
    aliasesFile: /usr/src/app/packages/synchronizer/dist/config/aliases/aliases.json
    typeMapFile: /usr/src/app/packages/synchronizer/dist/config/typeMap.json
    enrichment:
      enabled: false
      api: ""
      propertiesPath: ""
      aliasField: ""
      requestTimeoutMilliseconds: 5000

  dbs:
    s3:
      endpoint: ""
      region: us-east-1
      forcePathStyle: true
      sslEnabled: false
      sigVersion: v4
      storageClass: STANDARD
      bucket: ""
      fileName: ""
      layersVariable: layers
      accessKey: ""
      secretKey: ""
    sourceDb:
      host: localhost
      port: 5432
      username: postgres
      password: postgres
      database: postgres
      schema: public
      type: postgres
      sslAuth:
        enabled: false
        cert: ''
        key: ''
        root: ''
    destinationDb: *dbConfig

  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  mclabels: *mclabels
