{{- $releaseName := .Release.Name -}}
{{- $chartName := include "synchronizer.name" . -}}
{{- $cloudProviderFlavor := include "synchronizer.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "synchronizer.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "synchronizer.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "synchronizer.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synchronizer.fullname" . }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "synchronizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ include "synchronizer.fullname" . }}
      {{- include "synchronizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ include "synchronizer.fullname" . }}
        {{- include "synchronizer.labels" . | nindent 8 }}
      annotations:
        {{- include "mclabels.annotations" . | nindent 8 }}
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      containers:
        - name: {{ include "synchronizer.fullname" . }}
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          {{- if .Values.caSecretName }}
          env:
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "[%s/%s]" .Values.caPath .Values.caKey | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "synchronizer.fullname" . }}
            - secretRef:
                name: {{ include "synchronizer.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          volumeMounts:
            - name: layers-config
              mountPath: {{ .Values.env.layersFile | dir | quote }}
            - name: aliases-config
              mountPath: {{ .Values.env.aliasesFile | dir | quote }}
            {{- if .Values.typeMap.enabled }}
            - name: typemap-config
              mountPath: {{ .Values.env.typeMapFile | dir | quote }}
            {{- end }}
            - name: s3-downloads
              mountPath: /usr/src/app/packages/synchronizer/dist/src/common/s3/downloads
            {{- if .Values.dbs.sourceDb.sslAuth.enabled }}
            - name: source-db-cert-conf
              mountPath: /tmp/certs/source
              readOnly: true
            {{- end }}
            {{- if .Values.dbs.destinationDb.sslAuth.enabled }}
            - name: dest-db-cert-conf
              mountPath: /tmp/certs/dest
              readOnly: true
            {{- end }}
            {{- if .Values.caSecretName }}
            - mountPath: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
              name: root-ca
              subPath: {{ quote .Values.caKey }}
            {{- end }}
      volumes:
        - name: layers-config
          configMap:
            name: {{ include "synchronizer.fullname" . }}-layers
        - name: aliases-config
          configMap:
            name: {{ include "synchronizer.fullname" . }}-aliases
        {{- if .Values.typeMap.enabled }}
        - name: typemap-config
          configMap:
            name: {{ include "synchronizer.fullname" . }}-typemap
        {{- end }}
        - name: s3-downloads
          emptyDir: {}
        {{- if .Values.dbs.sourceDb.sslAuth.enabled }}
        - name: source-db-cert-conf
          secret:
            secretName: {{ .Values.dbs.sourceDb.sslAuth.secretName }}
        {{- end }}
         {{- if .Values.caSecretName }}
            - mountPath: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
              name: root-ca
              subPath: {{ quote .Values.caKey }}
            {{- end }}
        {{- if .Values.dbs.destinationDb.sslAuth.enabled }}
        - name: dest-db-cert-conf
          secret:
            secretName: {{ .Values.dbs.destinationDb.sslAuth.secretName }}
        {{- end }}
{{- end -}}
