{{- if .Values.enabled -}}
{{- $layersDir := .Values.env.layersDir -}}
{{- $namespaces := list -}}
{{- range .Values.namespaces -}}
{{- $namespaces = append $namespaces (merge (dict "layersFile" (printf "%s/%s.json" $layersDir .name)) (omit . "layers")) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synchronizer.fullname" . }}-namespaces
  labels:
    {{- include "synchronizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  production.json: {{ dict "namespaces" $namespaces | toPrettyJson | quote }}
{{- end }}
