{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synchronizer.fullname" . }}-namespaces
  labels:
    {{- include "synchronizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  production.json: {{ dict "namespaces" .Values.namespaces | toPrettyJson | quote }}
{{- end }}
